(function (global) {
    "use strict";
    const encoder = new TextEncoder();
    function esc(value) { return String(value || "").replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)").replace(/[\r\n]+/g, " ").replace(/[^\x20-\x7E]/g, character => ({ "–": "-", "—": "-", "’": "'", "“": '"', "”": '"' }[character] || "?")); }
    function wrap(text, width) {
        const out = []; String(text || "").split(/\n+/).forEach(paragraph => { let line = ""; paragraph.split(/\s+/).filter(Boolean).forEach(word => { const candidate = line ? `${line} ${word}` : word; if (candidate.length > width && line) { out.push(line); line = word; } else line = candidate; }); if (line) out.push(line); }); return out.length ? out : [""];
    }
    function buildPdf(report) {
        if (!report || !report.student || !report.indicators) throw new Error("Report data is incomplete.");
        const pages = []; let lines = [];
        const startPage = title => { if (lines.length) pages.push(lines); lines = [{ text: "Deborah Year 9 Civics and Citizenship", size: 9, colour: "0.12 0.20 0.28" }, { text: title, size: 18, colour: "0.12 0.20 0.28" }, { text: report.student.name, size: 11, colour: "0.35 0.39 0.43" }, { text: "", size: 5 }]; };
        const add = (text, options = {}) => { wrap(text, options.width || 92).forEach(value => { if (lines.length >= 46) startPage(options.continuedTitle || "Formative Learning Report — continued"); lines.push({ text: value, size: options.size || 10, bold: options.bold || false, colour: options.colour || "0.15 0.17 0.19", gap: options.gap || 0 }); }); };
        const heading = text => add(text, { size: 13, bold: true, colour: "0.12 0.20 0.28", gap: 4 });
        startPage("Formative Learning Report");
        add(`Student code: ${report.student.code || "Not displayed"}`); add(`Class: ${report.student.className || "Not recorded"}`); add(`Reporting period: ${report.student.reportingPeriod}`); add(`Generated: ${report.generatedDate}`);
        heading("Unit overview"); add("This formative report draws upon learning evidence collected across the Deborah Year 9 Civics and Citizenship unit."); add(`Lessons completed: ${report.overview.completed} of ${report.overview.available} (${report.overview.status})`); add(`Estimated active learning time: ${report.overview.activeTime}`); add(`Recorded sessions: ${report.overview.sessions}`);
        heading("Engagement profile"); if (report.engagement) { add(`${report.engagement.band} — confidence: ${report.engagement.confidence}`, { bold: true }); add(report.engagement.interpretation); add(`Completion consistency: ${report.engagement.completion}; longest focus-loss interval: ${report.engagement.longestFocus}.`); if (report.engagement.focus) add(report.engagement.focus); add(report.engagement.persistence); }
        startPage("Learning profile"); report.indicators.filter(item => !["Engagement", "Persistence", "Self-correction", "Metacognition", "Transfer of learning"].includes(item.name)).forEach(item => { add(`${item.name}: ${item.finalBand} (${item.confidence} confidence)`, { bold: true, gap: 2 }); add(item.teacherWording); });
        heading("Knowledge and progress"); add(`Average latest knowledge-check result: ${report.knowledge.latest}`); add(`Average highest result: ${report.knowledge.highest}`); add(`Recorded attempts: ${report.knowledge.attempts}`); add(report.knowledge.improvement); add(`Strongest recorded topic areas: ${report.knowledge.strongestTopics}`); add(`Areas requiring consolidation: ${report.knowledge.consolidationTopics}`);
        startPage("Learning behaviours and student work"); report.behaviours.forEach(item => { add(`${item.name}: ${item.band}`, { bold: true }); add(item.evidence); });
        heading("Evidence from student work"); if (!report.extracts.length) add("No student-work extracts were selected for this report."); report.extracts.forEach((item, index) => { add(`${index + 1}. ${item.label || item.fieldId} — ${item.lessonId}`, { bold: true }); add(`“${item.excerpt}”`); if (item.teacherNote) add(`Teacher context: ${item.teacherNote}`); });
        startPage("Strengths and next steps"); heading("Strengths"); report.strengths.forEach(item => add(`• ${item}`)); if (!report.strengths.length) add("No strengths have been entered."); heading("Next steps"); report.nextSteps.forEach(item => add(`• ${item}`)); if (!report.nextSteps.length) add("No next steps have been entered."); heading("Teacher comment"); add(report.teacherComment || "No teacher comment was added."); add(`Teacher: ${report.teacherName || "Not specified"}`); add(`Report generation date: ${report.generatedDate}`); heading("About this evidence"); add(report.dataNote, { size: 8, colour: "0.35 0.39 0.43" }); pages.push(lines);
        const objects = []; const addObject = value => { objects.push(value); return objects.length; };
        const font = addObject("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"); const boldFont = addObject("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>");
        const pageRefs = []; const contentRefs = [];
        pages.forEach((page, pageIndex) => { let y = 800; const commands = ["q", "0.75 0.64 0.25 RG", "1.2 w", "40 817 m 555 817 l S", "Q"]; page.forEach(line => { y -= (line.gap || 0); commands.push("BT", `/${line.bold ? "F2" : "F1"} ${line.size} Tf`, `${line.colour} rg`, `1 0 0 1 48 ${y} Tm`, `(${esc(line.text)}) Tj`, "ET"); y -= Math.max(11, line.size + 3); }); commands.push("BT", "/F1 8 Tf", "0.35 0.39 0.43 rg", `1 0 0 1 270 24 Tm`, `(Page ${pageIndex + 1} of ${pages.length}) Tj`, "ET"); const stream = commands.join("\n"); contentRefs.push(addObject(`<< /Length ${encoder.encode(stream).length} >>\nstream\n${stream}\nendstream`)); pageRefs.push(addObject("PENDING")); });
        const pagesRef = addObject(`<< /Type /Pages /Count ${pageRefs.length} /Kids [${pageRefs.map(ref => `${ref} 0 R`).join(" ")}] >>`); pageRefs.forEach((ref, index) => { objects[ref - 1] = `<< /Type /Page /Parent ${pagesRef} 0 R /MediaBox [0 0 595.28 841.89] /Resources << /Font << /F1 ${font} 0 R /F2 ${boldFont} 0 R >> >> /Contents ${contentRefs[index]} 0 R >>`; }); const catalog = addObject(`<< /Type /Catalog /Pages ${pagesRef} 0 R >>`);
        let pdf = "%PDF-1.4\n%Deborah\n"; const offsets = [0]; objects.forEach((object, index) => { offsets.push(encoder.encode(pdf).length); pdf += `${index + 1} 0 obj\n${object}\nendobj\n`; }); const xref = encoder.encode(pdf).length; pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n${offsets.slice(1).map(offset => `${String(offset).padStart(10, "0")} 00000 n `).join("\n")}\ntrailer\n<< /Size ${objects.length + 1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;
        return new Blob([encoder.encode(pdf)], { type: "application/pdf" });
    }
    function download(report) { const blob = buildPdf(report); const filename = global.DeborahReportingView.pdfFilename(report.student.name, report.generatedDate); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = filename; document.body.appendChild(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(link.href), 1000); return { filename, blob }; }
    function printFallback() { document.body.classList.add("printing-parent-report"); window.print(); setTimeout(() => document.body.classList.remove("printing-parent-report"), 500); }
    global.DeborahPdfReport = { buildPdf, download, printFallback };
})(window);
