const assert = require("node:assert/strict");
const fs = require("node:fs");
const vm = require("node:vm");
const context = { window: {}, Blob, TextEncoder, URL, setTimeout, console }; context.window = context; vm.createContext(context);
for (const file of ["js/reporting-config.js", "js/reporting-model.js", "js/reporting-view.js", "js/pdf-report.js"]) vm.runInContext(fs.readFileSync(file, "utf8"), context, { filename: file });
const response = "I recommend transparent Parliament scrutiny because evidence supports accountability. However, a counterargument concerns majority rule and minority rights. Therefore pluralism and the rule of law provide a qualified conclusion. <img src=x onerror=alert(1)>";
const records = Array.from({ length: 16 }, (_, index) => ({ lessonId: `week${Math.min(5, Math.floor(index / 4) + 1)}lesson${index % 4 + 1}`, lessonTitle: `Lesson ${index + 1}`, week: Math.min(5, Math.floor(index / 4) + 1), lesson: index % 4 + 1, studentUid: "student-1", sessionCount: 2, totalOpenTimeMs: 1200000, activeTimeMs: 900000, idleTimeMs: 180000, hiddenTimeMs: 120000, focusLossCount: 2, returnAfterFocusLossCount: 2, longestFocusLossMs: 70000, meaningfulInteractionCount: 18, revisionCount: 1, activitiesCompleted: ["who-should-act", "committee-evidence-list", ...(index > 12 ? ["final-belonging-charter", "whole-unit-systems-map", "national-portrait-brief"] : [])], knowledgeChecks: index > 2 ? { "knowledge-check": { attempts: [{ attemptNumber: 1, normalisedScore: .6 }, { attemptNumber: 2, normalisedScore: .85 }] } } : {}, highestKnowledgeScore: { normalisedScore: .85 }, writtenResponses: { reflection: { fieldId: "reflection", fieldLabel: "Reflection", currentText: response, wordCount: response.split(/\s+/).length, characterCount: response.length, revisionCount: 1 } }, unitProgress: { completed: true } }));
const profile = context.DeborahReportingModel.buildStudentFormativeProfile(records, { studentUid: "student-1", lessonsAvailable: 16 });
const saved = { includeFocus: false, strengths: ["Explains civic concepts clearly."], nextSteps: ["Compare more evidence."], teacherComment: "Consistent progress.", teacherName: "Ms Example", reportingPeriod: "Semester 2", extracts: [{ lessonId: records[0].lessonId, fieldId: "reflection", excerpt: response, label: "Thoughtful reflection", teacherNote: "Shows qualification." }], indicatorOverrides: { engagement: { selectedBand: "Generally consistent", evidenceStatement: "Completed substantial work.", reason: "PRIVATE OVERRIDE REASON", notReported: false } } };
const draft = context.DeborahReportingView.normaliseDraft(profile, saved);
assert.equal(draft.includeFocus, false);
assert.equal(draft.extracts.length, 1);
assert(context.DeborahReportingView.eligibleResponses(profile)[0].currentText.includes("<img"), "unsafe student markup remains data, not HTML");
const report = context.DeborahReportingView.parentReport(profile, { displayName: "A Student", accountCode: "S123456" }, { className: "9 Civics" }, draft);
assert.equal(report.engagement.focus, null, "teacher can exclude focus statistics");
assert(!JSON.stringify(report).includes("PRIVATE OVERRIDE REASON"), "internal override reason is absent from parent model");
assert(report.indicators.some(item => item.finalBand === "Generally consistent"), "override appears in parent model");
assert.equal(profile.rawEvidence.metrics.lessonsStarted, 16, "all lesson evidence remains available");
const filename = context.DeborahReportingView.pdfFilename("A Student", "2026-08-03");
assert.equal(filename, "Deborah_Year9_Civics_A_Student_2026-08-03.pdf");
(async () => {
    const blob = context.DeborahPdfReport.buildPdf(report); const bytes = Buffer.from(await blob.arrayBuffer()); const pdf = bytes.toString("latin1");
    fs.writeFileSync("/tmp/Deborah_Year9_Civics_A_Student_2026-08-03.pdf", bytes);
    assert(pdf.startsWith("%PDF-1.4")); assert(pdf.endsWith("%%EOF")); assert(pdf.includes("Formative Learning Report")); assert(pdf.includes("Strengths and next steps")); assert(pdf.includes("About this evidence")); assert(!pdf.includes("PRIVATE OVERRIDE REASON")); assert(!pdf.includes("Firestore"));
    const pages = (pdf.match(/\/Type \/Page\b/g) || []).length; assert(pages >= 4 && pages <= 8, `expected sensible pagination, got ${pages}`); assert.equal((pdf.match(/Page 1 of/g) || []).length, 1, "no blank duplicate first page");
    const longReport = JSON.parse(JSON.stringify(report)); longReport.extracts = Array.from({ length: 5 }, (_, i) => ({ lessonId: `lesson-${i}`, fieldId: "brief", label: `Extract ${i}`, excerpt: response.repeat(8), teacherNote: "Context note." })); const longPdf = Buffer.from(await context.DeborahPdfReport.buildPdf(longReport).arrayBuffer()).toString("latin1"); assert(longPdf.endsWith("%%EOF")); assert((longPdf.match(/\/Type \/Page\b/g) || []).length > pages, "long text flows onto additional pages");
    const source = fs.readFileSync("js/teacher-report.js", "utf8"); assert(!source.includes("innerHTML")); assert(!source.includes("localStorage")); assert(source.includes("waitForAuthenticatedProfile(\"teacher\")")); assert(source.includes("Move up") && source.includes("Move down"));
    const rosterSource = fs.readFileSync("js/class-roster.js", "utf8"); assert(rosterSource.includes('where("teacherUid", "==", user.uid)') && rosterSource.includes('where("classId", "==", classId)'), "roster query is teacher- and class-scoped at Firestore");
    const dashboard = fs.readFileSync("dashboard.html", "utf8"); assert(dashboard.includes('id="teacherTools" hidden') && dashboard.includes('profile.role === "teacher"'), "teacher controls default hidden and require a teacher profile");
    const dataSource = fs.readFileSync("js/reporting-data.js", "utf8"); assert(dataSource.includes('teacherReportReviews') && dataSource.includes('extracts:'), "drafts save separately with extracts");
    console.log(`PASS Stage 3 report workflow; synthetic PDF ${bytes.length} bytes, ${pages} pages`);
})().catch(error => { console.error(error); process.exitCode = 1; });
